#!/bin/bash

if readlink /proc/$$/fd/0 | grep -q "^pipe:"; then
	echo "$0: If you want to call this script from a pipe, you need to call"
	echo "    it with xargs(1) (see man xargs)"
	exit 1;
fi

if [ -z "$1" ]; then
	echo "Usage: $0 command"
	exit 1;
fi

command=$1
shift
$command "$@"
zenity --notification --text="Notif: $command completed."
